# Generated by Django 4.1.3 on 2023-03-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvitationEmail",
        ),
    ]
