version: '3.8'

services:

  postgres_db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  website:
    build: 
      context: ./
      dockerfile: ./website/Dockerfile
    volumes:
      - ./website:/website
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_NAME}
      - BROKER_URL=${REDIS_URL}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres_db
      - redis


volumes:
  postgres_db:
  redis: