# Generated by Django 4.1.3 on 2022-12-16 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergroup",
            name="administrator",
        ),
        migrations.AddField(
            model_name="usergroup",
            name="administrators",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
