# Generated by Django 4.1.3 on 2022-12-26 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="users_favorites",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="event.location",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organisers",
            field=models.ManyToManyField(
                related_name="events_organiser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                related_name="events_participant", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
