# Generated by Django 4.1.3 on 2023-01-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagebox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
