# Generated by Django 4.1.3 on 2023-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0002_messagetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_sent']},
        ),
    ]
