# Generated by Django 4.1.3 on 2023-03-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("messagebox", "0004_messagethread_user1_messagethread_user2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="messagebox.messagethread",
            ),
            preserve_default=False,
        ),
    ]
