# Generated by Django 4.1.3 on 2023-03-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("messagebox", "0005_message_thread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messagebox.messagethread",
            ),
        ),
    ]
