# Generated by Django 4.1.3 on 2023-03-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usergroup_administrators_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendinvitation",
            name="email_response_token",
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="email_response_token",
        ),
    ]
