# Generated by Django 4.1.3 on 2023-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventInvitation',
        ),
    ]
