# Generated by Django 4.1.3 on 2023-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_friendinvitation_email_response_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='email_response_token',
            field=models.CharField(default='fsjlkdfbalbserf', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='email_response_token',
            field=models.CharField(default='faldfuiabfulib', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
