# Generated by Django 4.1.3 on 2023-02-15 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_eventinvitation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["username"]},
        ),
        migrations.AddField(
            model_name="friendinvitation",
            name="date_sent",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendinvitation",
            name="response_received",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="date_sent",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="users.usergroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="response_received",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="friendinvitation",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupinvitation",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="administrators",
            field=models.ManyToManyField(
                related_name="groups_as_admin", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="members",
            field=models.ManyToManyField(
                related_name="groups_as_member", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
