# Generated by Django 4.1.3 on 2023-02-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_friendinvitation_id_alter_groupinvitation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
