# Generated by Django 4.1.3 on 2023-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventinvitation_email_response_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringeventschedule',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='email_response_token',
            field=models.CharField(default='hfalhfjd', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurringeventschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
    ]
